const mysql = require('mysql2/promise');

const booksData = [
  // LEMARI 3 RAK 1 NOVEL
  { title: "Rindu", author: "Tere Liye", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Long Last Yang Lama Hilang", author: "Harlan Coben", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Invitation Only", author: "Cecilia Wang", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "I'Ve Told Every Little Star", author: "Cecilia Wang", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "NowHere", author: "Pinkishdelight", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "So I Married A Senior", author: "Arista Vee", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Menahan Rasa", author: "Elsa Putri", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Dari Hati Yang Terdalam", author: "Indah Permatasari", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Cinta Yang Sederhana", author: "Ryan Bagus Lesmana", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Lasmi", author: "Nusya Kuswantin", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Musim Baru", author: "Roidah", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "A Case Of Love", author: "Quotesfangirl", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Schoolaholic Princess & Simfoni Cinta", author: "Yunisa KD", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Poetic December", author: "Tratih Pradnyaswari", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Segaris Rindu", author: "Sarah Aulia", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Untuk Matamu: Sekumpulan Puisi", author: "Kharisma P. Lanang", classification: "813", category: "Novel / Puisi", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Tak Sekedar Pulih", author: "Fadel Yulian", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Melepaskan", author: "Dindin Komarudin", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Cinta, Kita Yang Rasa", author: "Ariana Octavia", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Q & A", author: "Sherina Salsabila", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Rain And Flowers", author: "Tisa T S", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },
  { title: "Cinta Di Antara Kita Yang Tak Pandai Bicara", author: "Eru Wilanda", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1", stock: 1 },

  // LEMARI 3 RAK 1/1 NOVEL
  { title: "Dating Queen", author: "Ladrina Bagan", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1/1", stock: 1 },
  { title: "Pesta Terakhir", author: "Zulkifli L. Muchdi", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1/1", stock: 1 },
  { title: "Rapuh: Sebuah Cinta Pada Senja Kedua", author: "Farah Nuruzzahra", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1/1", stock: 1 },
  { title: "Blueberry Untuk Pauline", author: "Maya N'The Genk", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1/1", stock: 1 },
  { title: "Vacancy 2/2", author: "Pinkishdelight", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1/1", stock: 1 },
  { title: "Samantha", author: "Risa Saraswati", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1/1", stock: 1 },
  { title: "Ne, Sajangnim!", author: "Dekdi A", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1/1", stock: 1 },
  { title: "Begu Ganjang", author: "Ferdiriva Hamzah", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1/1", stock: 1 },
  { title: "2 Itu Teman 37 Itu Satu Kelas!", author: "Cartoonize", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1/1", stock: 1 },
  { title: "Rasa", author: "Nuril Basri", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1/1", stock: 1 },
  { title: "Kata: Tentang Senja yang Kehilangan Langitnya", author: "Rintik Sedu", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1/1", stock: 1 },
  { title: "Asmara Di Atas Haram", author: "Zulkifli L. Muchdi", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1/1", stock: 1 },
  { title: "Harmonies", author: "Temillasari Dwenti", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1/1", stock: 1 },
  { title: "Romantic Universe", author: "Dinan", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1/1", stock: 1 },
  { title: "Harapan di Atas Sajadah", author: "Mawar Malka", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1/1", stock: 1 },
  { title: "Me & Mr. Old", author: "Pipit Chie", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 1/1", stock: 1 },

  // LEMARI 3 RAK 2 NOVEL
  { title: "Malik & Elsa", author: "Boy Candra", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Racauan Yang Kusesali Untuk Kusyukuri", author: "Recvy Ineka Putra", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Pelabuhan Terakhir", author: "Roidah", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Aksara Hujan", author: "Ariqy Raihan", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Sore: Istri dari Masa Depan", author: "Suryana Paramita", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Bukan Rahasia Geez", author: "Rintik Sendu", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "40 Hari Takdir Itu Bernama Hidup dan Mati", author: "Adeigama", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Melangkah: Kisah yang Berakhir Luka", author: "Wisnu Widiatmoko", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Katanya Nikah Mudah", author: "Natasha Rizky", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Bias Rindu", author: "Elsa Syefira", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Nona Venus & Tuan Mars", author: "Dardawirdhaa", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Hadiah Perasaan", author: "Ivanasha", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Dalam Sketsa", author: "Ikrom Mustofa", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Kiara", author: "Dinni Adhiawaty", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Kekasih Halalmu", author: "Windy Irianti", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Sunyaruri", author: "Risa Saraswati", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Surga Kecil di Atas Awan", author: "Kirana Kejora", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Pekik Tanpa Irama", author: "Haidah", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Rumah Rindu", author: "K. Usman", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Tersesat dan Menemukan", author: "Ara Tiara", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Lebih Dari Rindu", author: "Aby A. Izzuddin", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Aku Benci Harus Merindu", author: "Putri Al Fatih", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Mengalahkan Hati", author: "Yusuf Hamdhani", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "My Lady 2", author: "Elya Handayani", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Antologi Cerpen dan Puisi Takdir", author: "Guru UPT SMAN 4 Parepare", classification: "813", category: "Antologi", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Mosaik Cinta Adira", author: "Mahrani", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Bulan Lebam di Tepian Toba", author: "Sihar Ramses Simatupang", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Pada Senja yang Membawamu Pergi", author: "Boy Candra", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Literasi Hati", author: "Ichwannul Suenta", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Kutatap Engkau di Kegelapan Malam", author: "Rusmiati Lamma", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Hujan Punya Cerita Tentang Kita", author: "Yoana Dianika", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Lengking Kematian", author: "Marlina Lin", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },
  { title: "Countless Love", author: "Fala Amelina", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2", stock: 1 },

  // LEMARI 3 RAK 2/2 NOVEL
  { title: "With You", author: "Imhyera", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Espresso", author: "Bernard Batubara", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "The Proposal", author: "Dekdi A", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Malachai", author: "A-Noona", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Our Years", author: "Sirhayani", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Untukmu di Hari Kemarin", author: "Galih Hidayatullah", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Jurnal Risa: Teror Liburan Sekolah", author: "Risa Saraswati", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Guardiationship: Silver Lining of the Cloud", author: "Renita", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Pesan Kematian: Dia Ingin Didengar", author: "Cerberus Plouton", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Setelah Dia Pergi", author: "Dedy Chandra H", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Back To Love", author: "Kaka Hy", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Rumah Bangtan", author: "Mayang Aeni", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Blue Serenade", author: "Dini Marlina", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Eufloria", author: "Asabell Audida", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Mario", author: "Cecilia Wang", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "I'm Not Fine", author: "Elda Rina", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Story of Seth", author: "Wulanfadi", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "DeEn AsSalam", author: "Aby A. Izzuddin", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Kita Pernah Salah", author: "Fuadbakh", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Durasi", author: "Desi Mayang Sari", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "My Stupid Boss 6: be like Bob", author: "Chaos", classification: "813", category: "Novel Komedi", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Seoulsister", author: "Yannie Kim", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Happy Little Soul", author: "Retnohening", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Memang Modus: jungkir balik si Tukang Gombal", author: "Bram Dermawan", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Sabar & Syukur Tanpa Kopi", author: "Taufik Aulia", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Evolusi Rindu: Ruang Sepi dan Dirimu", author: "Gentakiswara", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Singgah", author: "Diarihidupkita", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Jatuh Cinta Bukan Sebuah Rencana", author: "Ai Deti Lestari", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },
  { title: "Cincin Cinta Miss Titian", author: "Hermawan Aksan", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 2/2", stock: 1 },

  // LEMARI 3 RAK 3 NOVEL
  { title: "Diary Arwah", author: "Margaluwih", classification: "813", category: "Novel Horor", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Gitanjali", author: "Febrialdi R", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Love Line", author: "Nambyull", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Marmut Merah Jambu", author: "Raditya Dika", classification: "813", category: "Novel Komedi", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Babi Ngesot", author: "Raditya Dika", classification: "813", category: "Novel Komedi", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Spiritual Anak Cucu Adam", author: "Gibran", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Kami (Bukan) Jongos Berdasi", author: "J.S. Khairen", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "The Last Barongsay", author: "Pere Sumbada", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Nefertari Sang Ratu Heretik", author: "Michelle Moran", classification: "813", category: "Novel Sejarah", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Deru Gunung: Gelora Cinta Usia Senja", author: "Yasunari", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Dalam Kurang", author: "Haditha", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Me And My Broken Heart", author: "Wulanfadi", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Never Give Up!", author: "Ayum Daigo", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Lipstick", author: "Inkarnadine", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Tertawa Ala Persia", author: "Firoozeh Dumas", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Wisecrack", author: "H Yonashi", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Jerom", author: "Cecilia Wang", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "More Than Friends", author: "Pramesti Luvi", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Iya, Pak!", author: "Helyu L.A", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 2 },
  { title: "Lacuna", author: "H Yonashi", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Bangtan's New Manager", author: "Bang Mirne", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Halusinasiku", author: "Rusmiati Lamma", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Belajarlah Menyatakan Cinta", author: "Jon Hariyadi", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Selepas Kita", author: "Elda Rina", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Rindu Tak Semestinya", author: "Abdul Halim", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 2 },
  { title: "Tears Spring in Korea", author: "Dwi Andhika", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Doriyaki Rasa Baru", author: "Dorippu", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Cinta Empat Bab", author: "Hermawan Aksan", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },
  { title: "Pulau Huntu", author: "Iwok Abqary's", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3", stock: 1 },

  // LEMARI 3 RAK 3/3 NOVEL
  { title: "Ivanna Van Dijk", author: "Risa Saraswati", classification: "813", category: "Novel Horor", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Marianne", author: "Risa Saraswati", classification: "813", category: "Novel Horor", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Maddah", author: "Risa Saraswati", classification: "813", category: "Novel Horor", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Asih", author: "Risa Saraswati", classification: "813", category: "Novel Horor", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Wanita, Luka, dan Akhir yang Bahagia", author: "Tia Setiawati", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Separuh Hati yang Pergi", author: "Mimie Sarah", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "EX: Balikan sama saja mengulang kisah yang sama!", author: "Umi Wandira Gajah", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Fre&Fer", author: "Rishaatp", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Harap", author: "Elda Rina", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "My Demian", author: "Motterial Ziacky", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Ibu & Kue Lebaran", author: "Aji Nur Afifah", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Satu Hari di 2018", author: "Boy Candra", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "My Little Bettersweet Wife", author: "H Yonashi", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Amour Vrai", author: "Naomi Octa", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Amanda", author: "Ami Rahmi", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Tempat Pulang", author: "Yusuf Filasafa", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Happy Little Soul Edisi Terbaru", author: "Retnohening", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Mencintaimu Sedalam Lukaku", author: "A'Yat Khalili", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Bahagia Tanpa Kita", author: "Katrina Vabiola", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Si Kumal 1% Gemas, 99% Pulas", author: "Dipa Utomo", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Terangkai Saat Dia Sedang Tidur", author: "Zarry Hendrik", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 3/3", stock: 1 },
  { title: "Generasi Micin VS Kevin", author: "Faza Meonik", classification: "813", category: "Novel Komedi", shelf: "Lemari 3, Rak 3/3", stock: 1 },

  // LEMARI 3 RAK 4 NOVEL
  { title: "Perempuan Teduh", author: "Haruntsaqif", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Cinta yang Kupeluk Sepanjang Waktu", author: "Lumatul Fitria", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Aku Mencintaimu Seluas Ikhlasku Melepaskanmu", author: "Sarah Aulia", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Surat Untuk Yang Pernah Patah Hati", author: "Peyempuan", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Jika Nanti Aku Jatuh Cinta Lagi", author: "Istiana", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Pengabdi Netijen", author: "Geraldy Tan", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Aku Memilih Pergi", author: "Tereza Fahlevi", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Aku yang Pernah Terluka", author: "Rina Yunita", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "The Book Of Almost", author: "Brian Khrisna", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Resah: Menenangkan Rindu Atas Rasa Yang Pergi", author: "Roni Komara", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Takkan Mampu Bersandiwara", author: "Roem Rowie", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Epilog Rasa: Aku adalah hati yang mengharap rindu", author: "Desi Suryana", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "My Stupid Boss 4", author: "Chaos", classification: "813", category: "Novel Komedi", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Afeksi: Aku Merindukanmu dari jauh meski jarak sangat dekat", author: "Zaka Bagas Wirawan", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Arial & Adara", author: "Helobagas", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Kita Udahan Aja!", author: "Tamavanda", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Cerita Kulkas", author: "Shindy Farrahdiba", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Sinkron", author: "Maharapall", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Jeda", author: "Andre Rianda", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Senandung", author: "Putri Al-Fatih", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Hatsukoi", author: "Akashisedai", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Mati di Jogyakarta", author: "Egha De Latoya", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Fase: Kesulitan itu ada bukan untuk membuatmu payah", author: "Istiana", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Bercakap dengan Kesunyian", author: "Danang Apriyan", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Meremuk Peluk", author: "Rena Kharisma", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Yang Kedua", author: "Lani Utami", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Jangan Sembunyi Di Bumi", author: "Dionisius", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Jarak Menolak Temu", author: "Euis N. Hayati", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Wonderful You", author: "Sobat Muslimah", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Menetaplah, Jangan Sebatas Menemani", author: "Jeffry Shandy", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "My Stupid Boss 2", author: "Chaos", classification: "813", category: "Novel Komedi", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Kenang", author: "Arief Aumar", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },
  { title: "Nafsu Terakhir", author: "Elizabeth D. Inandiak", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4", stock: 1 },

  // LEMARI 3 RAK 4/4 NOVEL
  { title: "The Purpose Of Life", author: "Alnira", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Rasa Dalam Diam", author: "Saipul El-Mizu", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Di Atas Luka Yang Sama", author: "Ditia Muara Intan", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Lebih Dari Luka", author: "Ai Deti Lestari", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Cinta Yang Tak Biasa", author: "Natta Reza", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Puncak Nasi Tumpeng", author: "Fico Fachriza", classification: "813", category: "Novel Komedi", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Karung Nyawa", author: "Haditha", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Distilasi Alkena", author: "Wira Nagara", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Always The Bride: Pengantin Baru (Lagi)", author: "Jessica Fox", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Tentang Rindu Yang Melangit", author: "Budy Satria Dkk", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Travelers' Tale Belok Kanan, Barcelona!", author: "Adhitya Mulya Dkk", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Pelangi Bulan", author: "Maradilla Syachridar", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "120 Ways To Be Ikhlas", author: "Ayumdaigo", classification: "813", category: "Novel Inspiratif", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Tajir Melintir", author: "Mardigu WP", classification: "813", category: "Novel Inspiratif", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Sempurna Separuh", author: "Rizqi Awal", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Lost On Everest", author: "Vanny Chrisma W.", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Dua Satu II.I", author: "Bio One", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Kepada Masa Lalu", author: "Kiciks.ID", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Lelaki Tegar: Menuntun Langkah Menuju Berkah", author: "Haruntsaqif", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Janji", author: "Fadel Yulian", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Cinderbella: Bukan Sebuah Dongeng Patah Hati", author: "Cantika ZHR", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Near", author: "Citra Novy", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Gincu: Sebuah Komedi Romantis", author: "LM Cendana", classification: "813", category: "Novel Komedi", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "Hey, Sab!", author: "Ra Emira", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },
  { title: "I'm Yours: Cinta dan Rasa Sakit itu Saling Mengikuti", author: "Putri Lagilagi", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 4/4", stock: 1 },

  // LEMARI 3 RAK 5 NOVEL
  { title: "Miss Parnowati", author: "Very Barus", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Jejak Kala", author: "Anindita S. Thayf", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Kita: Kisah yang terpaksa usai", author: "Dindi Lekstami", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Potongan: Di dalam siklus, kita bukanlah sirkus", author: "Atap", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Hilang: Sebuah Kekalahan Tanpa Pemenang", author: "Nawang Nidlo Titisari", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Nelangsa: Ruang sendiri untuk mengenang yang telah pergi", author: "Gentakiswara", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "The Pain Of Love", author: "Arini Ramadhanti", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "William", author: "Risa Saraswati", classification: "813", category: "Novel Horor", shelf: "Lemari 3, Rak 5", stock: 2 },
  { title: "Setelah 7 Wanita Menamparku", author: "Anak S-E-N", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Meredam Dendam", author: "Gerson Poyk", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Sastra Jendra Hayuningrat Pangruwating Diyu", author: "Agus Sunyoto", classification: "813", category: "Novel Sejarah", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Mimpi Anak Pulau", author: "Abidah El Khalieqy", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Night Talks Before Go To Sleep", author: "Helo Bagas", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Night: Kesaksian Tentang Holocaust", author: "Elie Wiesel", classification: "813", category: "Novel Sejarah", shelf: "Lemari 3, Rak 5", stock: 3 },
  { title: "Renung", author: "Tengku Novenia Yahya", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Senjakala", author: "Risa Saraswati", classification: "813", category: "Novel Horor", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Istiqomah Until Husnul Khotimah", author: "Ririn Astutiningrum", classification: "813", category: "Novel Religi", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Mencintai (untuk) Patah Hati", author: "Stefani Bella", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Titik Lemah", author: "Zarry Hendrik", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Sesekali Kita Butuh Sepi", author: "Ikhsanudin", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Yang Mesti Dibenci itu Cinta", author: "Albait Mubaroo", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Asa: Sebuah janji untuk menghapus luka", author: "Eru Wilanda", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Candala", author: "Zia Ulhaq", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Ambigu", author: "Maharapall", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Hidup: Semua indah pada waktunya", author: "Ikhsanudin", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Jemu", author: "Namhar", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Museum Of Broken Heart", author: "Brian Khrisna", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Bajak Laut Mahapatih", author: "Adhitya Mulya", classification: "813", category: "Novel Petualangan", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Eufloria Bloom With Luv", author: "Asabell Audida", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "High Heels", author: "Inkarnadine", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Tenung", author: "Dimas Tri Aditiyo", classification: "813", category: "Novel Horor", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Atas Nama Cinta Aku Merelakan", author: "Kang Ihsan", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },
  { title: "Clade", author: "Cantika Zhr", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5", stock: 1 },

  // LEMARI 3 RAK 5/5 NOVEL
  { title: "Jika Kita Tak Pernah Jatuh Cinta", author: "Alvi Syahrin", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Sewu Dino", author: "Simpleman", classification: "813", category: "Novel Horor", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Kamu Gak Sendiri", author: "Syahid Muhammad", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Egosentris", author: "Syahid Muhammad", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Derana", author: "Wirasakti Setyawan", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Kalandara", author: "Gentakiswara", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Paradigma", author: "Syahid Muhammad", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Arah Langkah", author: "Fiersa Besari", classification: "813", category: "Novel Petualangan", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Hilang Arah", author: "Sdavincii", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Senyawa", author: "Sdavincii", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Tapak Jejak", author: "Fiersa Besari", classification: "813", category: "Novel Petualangan", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Persimpangan", author: "Hasan Aspahani", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "My Choice", author: "Putu Anjani", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Amor Fati", author: "Stefani Bella", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Nepenthe", author: "Yustika M", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Bukan Golongan Kami", author: "Coki Pardede", classification: "813", category: "Novel Komedi", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Reaper", author: "Yume Yun", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Katarsis Hitam Putih", author: "Walang Gustiyala", classification: "813", category: "Novel", shelf: "Lemari 3, Rak 5/5", stock: 1 },
  { title: "Penangsang Tarian Rembulan Luka", author: "Nasirun Purwokartun", classification: "813", category: "Novel Sejarah", shelf: "Lemari 3, Rak 5/5", stock: 1 }
];

async function seed() {
  console.log('🔄 Menjalankan seeder gabungan (30 buku INLISLite + 261 buku Lemari 3 + Foto Sampul)...');
  require('./merge_all_books.js');
}

seed().catch(err => {
  console.error('Error saat seed:', err);
});

